"use client";
import { useContent } from '../../content/ContentProvider';
import { assets } from '../../content/assets';
import { Lang, url } from '../../content/site';
import { Button } from '../../components/Ui';
export default function Hero({ l }: {
    l: Lang;
}) { const { pick, content } = useContent(); return <section className="hero hero-editorial"><div className="hero-topline"><span>BERLIN · FOOD BRAND PARTNERSHIPS</span><span>{pick(l, 'BESTEHENDE KÜCHEN. NEUE IDEEN.', 'EXISTING KITCHENS. NEW IDEAS.')}</span></div><div className="hero-copy"><span className="eyebrow">{pick(l, 'BRING NEUE FOOD-MARKEN IN DEINE KÜCHE.', 'BRING NEW FOOD BRANDS TO YOUR KITCHEN.')}</span><h1><span>{pick(l, 'DEINE KÜCHE.', 'YOUR KITCHEN.')}</span><span className="hero-outline">{pick(l, 'NEUE MARKEN.', 'NEW BRANDS.')}</span><span className="hero-accent">{pick(l, 'VIEL GESCHMACK.', 'BIG FLAVOUR.')}</span></h1><div className="hero-bottom-copy"><p>{pick(l, 'Deine Küche hat Möglichkeiten. UCV bringt Food-Marken, Menüs und persönliche Begleitung. Dein Team bringt den Geschmack.', 'Your kitchen has possibilities. UCV brings food brands, menus and personal support. Your team brings the flavour.')}</p><div><Button l={l}/><a className="hero-secondary" href={url(l, 'brands')}>{pick(l, 'Unsere Marken entdecken', 'Explore our brands')}</a></div></div></div><div className="hero-food-stage" aria-hidden="true"><div className="food-orbit orbit-one"/><div className="food-orbit orbit-two"/><div className="food-spotlight"/><img className="hero-food-cutout" src={content.images.hero || assets.hero} alt=""/><div className="food-note">CRISPY.<br />BOLD.<br /><i>REBELS.</i></div><div className="rotating-label"><span>FOOD BRANDS · BERLIN ·</span><b>UCV</b></div></div><div className="hero-footline"><span>{pick(l, 'DU KOCHST. WIR BEGLEITEN.', 'YOU COOK. WE SUPPORT.')}</span><a href="#brands"><span className="scroll-line"/>{pick(l, 'WEITER ENTDECKEN', 'KEEP EXPLORING')}</a><span>DE / EN</span></div></section>; }

